---
kind: pipeline
type: docker
trigger:
  event:
  - push
  branch:
  - master
name: publish-docs

clone:
  depth: 1

image_pull_secrets:
- zm_git_docker_public

steps:
- name: Generate docs
  image: docker.pkg.github.com/zyra/zmdocs/zmdocs:v1.1.1
  when:
    branch:
    - master
  commands:
  - zmdocs g

- name: Publish docs
  image: plugins/gh-pages
  when:
    branch:
    - master
  settings:
    username:
      from_secret: gh_user
    password:
      from_secret: gh_token
    pages_directory: docs
---
kind: signature
hmac: ee12c4bc40522482cb0c1cac667ba5ab8faba67e031865d75c96632ae29c41ae

...
