name: Build

on:
- push

jobs:
  default:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Install node_modules
      run: |
        npm ci
        npx lerna bootstrap

    - name: Build Capacitor project
      working-directory: ./packages/plugin
      run: npm run build

    #- name: Test web implementation
    #  working-directory: ./packages/plugin
    #  env:
    #    STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
    #    STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
    #  run: npm test

    - name: Build Ionic app
      working-directory: ./packages/test
      run: npm run build

    - name: Update & Sync Capacitor Project
      working-directory: ./packages/test
      run: npx cap update android && npx cap sync android

    - name: Build Android Debug APK
      working-directory: ./packages/test/android
      run: ./gradlew assembleDebug
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        path: ./packages/test/android/app/build/outputs/apk/debug/app-debug.apk
